# Generated by Django 5.1.3 on 2024-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='main.course'),
        ),
    ]
